#!/bin/bash
# SessionStart hook: write instruction shard + probe Chrome connection
# set -euo pipefail  # removed: races with plugin autoUpdate cache swap
HOOK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ROOT="$(dirname "$HOOK_DIR")"
# Probe the Chrome backend first (2s timeout, best-effort), because the shard
# depends on it: since the one-plugin fold (bds-jakemi) every batterie user gets
# passe, most with no browser backend, and "Never WebFetch" is wrong advice there.
# Subagents skip the probe — they inherit the parent's knowledge — and leave the
# state unknown, which writes the shard unqualified as before.
STATE="unknown"
CONN_STATUS=""
if [ -z "${CLAUDE_SUBAGENT:-}" ]; then
    if command -v passe &>/dev/null; then
        CONN_STATUS=$(timeout 2 passe status 2>/dev/null || true)
    fi
    if echo "$CONN_STATUS" | grep -q "reachable=True"; then STATE="reachable"; else STATE="unreachable"; fi
fi

# The shard is a hook-generated REGULAR FILE, not a symlink (passe-mezigo):
# a symlink into the plugin root dangles on every version bump until the
# next session, and dangled permanently when the install root was ephemeral
# (the Cowork-sandbox incident, dead for a week). A copy can only go stale,
# and this rewrite refreshes it every session start — same pattern as mise.
if [ -f "$PLUGIN_ROOT/instructions.md" ]; then
    mkdir -p "${CLAUDE_CONFIG_DIR:-$HOME/.claude}/rules"
    RULES_FILE="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/rules/passe.md"
    # Remove any leftover symlink first — writing through one would clobber
    # its target (e.g. a working-tree instructions.md), not replace the link.
    rm -f "$RULES_FILE"
    {
        echo "<!-- Generated by the passe plugin's session-start.sh —"
        echo "     rewritten from the plugin's instructions.md every session."
        echo "     Edit the source in spm1001/passe, not this copy. -->"
        echo ""
        if [ "$STATE" = "unreachable" ]; then
            echo "> **No browser backend was reachable when this session started** (\`passe status\` said"
            echo "> reachable=False, or the passe CLI is missing). Until one is, the WebFetch override below"
            echo "> does not apply: use WebFetch as normal, and reach for passe only once a backend is set up."
            echo ""
        fi
        cat "$PLUGIN_ROOT/instructions.md"
    } > "$RULES_FILE"
fi

# Surface connection state. Unreachable is news only where a backend is expected
# (PASSE_CDP set); everywhere else it is the normal case and stays silent.
DETAIL=""
if [ "$STATE" = "reachable" ]; then
    CHROME_VER=$(echo "$CONN_STATUS" | grep chrome_version | sed 's/.*=//')
    TABS=$(echo "$CONN_STATUS" | grep tabs_open | sed 's/.*=//')
    DETAIL="Chrome connected: ${CHROME_VER}, ${TABS} tab(s)"
elif [ "$STATE" = "unreachable" ] && [ -n "${PASSE_CDP:-}" ]; then
    DETAIL="Chrome unreachable at PASSE_CDP=${PASSE_CDP} — run 'passe status' for diagnostics; check the backend unit is up, or 'passe login <url>' starts a visible local Chrome"
fi
if [ -n "$DETAIL" ]; then
    cat <<EOF
{"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": "${DETAIL}"}}
EOF
fi

# Consume stdin (hook protocol)
cat > /dev/null
exit 0
